
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jljhtvfrkxehvdvhfktv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsamh0dmZya3hlaHZkdmhma3R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzc0MzgsImV4cCI6MjA1OTY1MzQzOH0.No4bnq7PUvkeNMZliZx8QV-KEEemjcwaw_HfBT0bqrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create a standalone supabase instance for offline sync operations to avoid circular imports
export const supabaseSync = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Deprecated: Use supabaseSync directly instead
export function getSupabaseForSync() {
  return supabaseSync;
}
